configMapGenerator:
- files:
  - application.yml
  name: 82259371-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: ce82259371acr.azurecr.io/82259371
  newTag: "202411200030"
- name: ce82259371acr.azurecr.io/82259371
  newTag: "202411250535"
